"""
Workshop Content Generator
Fetches all addon IDs from a Steam Workshop collection and writes a
ready-to-use workshop_content.lua for your GMod DS.
"""

import urllib.request
import urllib.parse
import json
import sys
import os

OUTPUT_FILE = "workshop_content.lua"

HEADER = """-- Workshop Content Downloader
-- Auto-generated by workshop_gen.py
-- Forces clients to download all addons from your collection.

if not SERVER then return end

"""

def fetch_collection(collection_id: str) -> list[dict]:
    url = "https://api.steampowered.com/ISteamRemoteStorage/GetCollectionDetails/v1/"
    data = urllib.parse.urlencode({
        "collectioncount": "1",
        "publishedfileids[0]": collection_id,
    }).encode()

    req = urllib.request.Request(url, data=data, method="POST")
    with urllib.request.urlopen(req, timeout=15) as resp:
        body = json.loads(resp.read().decode())

    details = (
        body
        .get("response", {})
        .get("collectiondetails", [{}])[0]
    )

    if "children" not in details:
        raise ValueError(f"No children found — is '{collection_id}' a valid collection ID?")

    return details["children"]


def fetch_item_names(file_ids: list[str]) -> dict[str, str]:
    """Batch-fetch display names for up to 100 items at a time."""
    names = {}
    chunk_size = 100
    for i in range(0, len(file_ids), chunk_size):
        chunk = file_ids[i:i + chunk_size]
        data = {"itemcount": str(len(chunk))}
        for j, fid in enumerate(chunk):
            data[f"publishedfileids[{j}]"] = fid
        encoded = urllib.parse.urlencode(data).encode()
        req = urllib.request.Request(
            "https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/",
            data=encoded, method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                body = json.loads(resp.read().decode())
            for item in body.get("response", {}).get("publishedfiledetails", []):
                fid = item.get("publishedfileid", "")
                title = item.get("title", "").strip()
                if fid and title:
                    names[fid] = title
        except Exception:
            pass  # Names are cosmetic — don't fail on this
    return names


def write_lua(children: list[dict], names: dict[str, str], out_path: str):
    lines = [HEADER]
    for item in children:
        fid = item.get("publishedfileid", "")
        if not fid:
            continue
        name = names.get(fid, "")
        comment = f"  -- {name}" if name else ""
        lines.append(f'resource.AddWorkshop( "{fid}" ){comment}\n')

    with open(out_path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def main():
    if len(sys.argv) < 2:
        collection_id = input("Enter collection ID (or full URL): ").strip()
    else:
        collection_id = sys.argv[1].strip()

    # Accept full URL
    if "id=" in collection_id:
        collection_id = collection_id.split("id=")[-1].split("&")[0]

    print(f"Fetching collection {collection_id}...")
    children = fetch_collection(collection_id)
    file_ids = [c["publishedfileid"] for c in children if "publishedfileid" in c]
    print(f"Found {len(file_ids)} item(s). Fetching names...")

    names = fetch_item_names(file_ids)

    out_path = os.path.join(os.path.dirname(__file__), OUTPUT_FILE)
    write_lua(children, names, out_path)
    print(f"Done! Written to: {out_path}")


if __name__ == "__main__":
    main()
